name: PR Checks

on:
  pull_request:
    types:
      - opened

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

  code-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.0

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 8.0.0

      - name: Check code style
        run: dotnet format --check

  pr-checks:
    runs-on: ubuntu-latest
    needs: [build-and-test, code-style-check]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PR Checks
        run: echo "All checks passed!"